#!/bin/bash
clear
########## COLOR ##########
ORANGE='\033[0;33m'
pp="\033[42m"
xz="\033[1;93m"
z="\033[96m"
NC="\033[0m"
g="\033[1;92m"
y='\033[1;33m' #yellow
YELL='\033[0;33m'
breed='\033[1;31m'
bwhite='\033[1;37m'
bblue="\033[1;34m"
bgreen='\033[1;32m'

clear
IPVPES="https://raw.githubusercontent.com/gemilangkinasih/Autoscript/GM/Register"
clear
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/gemilangkinasih/Autoscript/GM/Register"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m════════════════════════════════════════════\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m════════════════════════════════════════════\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/+6287786741106"
    echo -e "\033[1;93m════════════════════════════════════════════\033[0m"
    exit 0
  fi
}
checking_sc
clear
echo -e " ${NC} ╭══════════════════════════════════════════╮"
echo -e " ${NC} │$bwhite\033[41m              MENU MANAGER BOT             ${NC}│"
echo -e " ${NC} ╰══════════════════════════════════════════╯"
echo -e " ${NC} ╭══════════════════════════════════════════╮\033[0m"
echo -e " ${NC} │ ${NC}[${BRED}01${NC}]${NC} Menu BOT Panel${NC}"
echo -e " ${NC} │ ${NC}[${BRED}02${NC}]${NC} Menu BOT Notifikasi${NC}"
echo -e " ${NC} │ ${NC}[${BRED}03${NC}]${NC} Menu BOT Backup${NC}"
echo -e " ${NC} │ ${NC}[${BRED}04${NC}]${NC} Exit Menu BOT${NC}"
echo -e " ${NC} ╰══════════════════════════════════════════╯\033[0m"
echo -e ""
read -p " ${NC} Select From Options [ 1-3 / 4 ] ❱❱❱ " menu
case $menu in
1) clear ; checking_sc ; mbot-panel ;;
2) clear ; checking_sc ; bot ;;
3) clear ; checking_sc ; 
echo -e "Note: "
echo -e "Sebelum Menggunakan BOT Backup"
echo -e "Harap Setup Dulu ID & Bot Token Kamu !"
sleep 2
mbot-backup ;;
0 | 4 ) menu ;;
*) m-bot ;;
esac