#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
YELL='\033[0;33m'
breed='\033[1;31m'
bwhite='\033[1;37m'
bblue="\033[1;34m"
bgreen='\033[1;32m'

red() { echo -e "\\033[32;1m${*}\\033[0m"; }
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/gemilangkinasih/Autoscript/GM/Register"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m════════════════════════════════════════════\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m════════════════════════════════════════════\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/+6287786741106"
    echo -e "\033[1;93m════════════════════════════════════════════\033[0m"
    exit 0
  fi
}

checking_sc
clear
echo -e " ${NC} ╭══════════════════════════════════════════╮"
echo -e " ${NC} │$bwhite\033[41m             MENU MANAGER SSH             ${NC}│"
echo -e " ${NC} ╰══════════════════════════════════════════╯"
echo -e " ${NC} ╭══════════════════════════════════════════╮\033[0m"
echo -e " ${NC} │ ${NC}[${BRED}01${NC}]${NC} Create Account Trojan WS/GRPC${NC}"
echo -e " ${NC} │ ${NC}[${BRED}02${NC}]${NC} Create Trial Trojan WS/GRPC${NC}"
echo -e " ${NC} │ ${NC}[${BRED}03${NC}]${NC} DeleteAccount Trojan WS/GRPC${NC}"
echo -e " ${NC} │ ${NC}[${BRED}04${NC}]${NC} Renew Trojan Account${NC}"
echo -e " ${NC} │ ${NC}[${BRED}05${NC}]${NC} Check Trojan login Account${NC}"
echo -e " ${NC} │ ${NC}[${BRED}06${NC}]${NC} ComeBack Menu${NC}"
echo -e " ${NC} ╰══════════════════════════════════════════╯\033[0m"
echo -e ""
read -p " ${NC} Select From Options [ 1-5 / 6 ] ❱❱❱ " menu
case $menu in

1)
    addtr
    ;;
2)
    trialtr
    ;;
3)
    deltr
    ;;
4)
    renewtr
    ;;
5)
    cektr
    ;;
*)
    menu
    ;;
esac
