#!/bin/bash
# COLOR VALIDATION
clear
y='\033[1;33m' #yellow
BGX="\033[42m"
CYAN="\033[96m"
z="\033[96m"
f="\033[1;97;41m"
RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[0;34m"
green='\033[0;32m'
grenbo="\e[92;1m"
purple="\033[95m"
YELL='\033[0;33m'
breed='\033[1;31m'
bwhite='\033[1;37m'
bblue="\033[1;34m"
bgreen='\033[1;32m'

# // INTALLER-UDP
UDPX="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d-%m-%Y')
TIMEZONE=$(printf '%(%H-%M-%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
clear
MYIP=$(curl -sS ipv4.icanhazip.com)
echo ""
izinsc="https://raw.githubusercontent.com/gemilangkinasih/Autoscript/GM/Register"
# USERNAME
rm -f /usr/bin/user
username=$(curl ${izinsc} | grep $MYIP | awk '{print $2}')
echo "$username" >/usr/bin/user
# validity
rm -f /usr/bin/e
valid=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
echo "$valid" >/usr/bin/e
# DETAIL ORDER
username=$(cat /usr/bin/user)
oid=$(cat /usr/bin/ver)
exp=$(cat /usr/bin/e)
clear
# CERTIFICATE STATUS
d1=$(date -d "$valid" +%s)
d2=$(date -d "$today" +%s)
certifacate=$(((d1 - d2) / 86400))
# VPS Information
DATE=$(date +'%Y-%m-%d')
datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo -e "$COLOR1 $NC Expiry In   : $(( (d1 - d2) / 86400 )) Days"
}
mai="datediff "$Exp" "$DATE""

# Status Expired Or Active
Info="(${green}Active${NC})"
Error="(${RED}Expired${NC})"
today=`date -d "0 days" +"%Y-%m-%d"`
Exp1=$(curl ${izinsc} | grep $MYIP | awk '{print $3}')
if [[ $today < $Exp1 ]]; then
sts="${Info}"
else
sts="${Error}"
fi
clear

# OS Uptime
uptime="$(uptime -p | cut -d " " -f 2-10)"

# Getting CPU Information
cpu_usage1="$(ps aux | awk 'BEGIN {sum=0} {sum+=$3}; END {print sum}')"
cpu_usage="$((${cpu_usage1/\.*} / ${coREDiilik:-1}))"
cpu_usage+=" %"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
WKT=$(curl -s ipinfo.io/timezone )
DAY=$(date +%A)
DATE=$(date +%m/%d/%Y)
DATE2=$(date -R | cut -d " " -f -5)
IPVPS=$(curl -s ipv4.icanhazip.com)
cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
tram=$( free -m | awk 'NR==2 {print $2}' )
uram=$( free -m | awk 'NR==2 {print $3}' )
fram=$( free -m | awk 'NR==2 {print $4}' )
clear
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#Status | Geo Project
clear
# // STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${YELL}ON✓${NC}"
else
   status_ssh="${RED}🔴${NC} "
fi

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${YELL}ON✓${NC}"
else
    status_ws_epro="${RED}🔴${NC} "
fi

# // STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${YELL}ON✓${NC}"
else
   status_haproxy="${RED}🔴${NC} "
fi

# // STATUS SERVICE XRAY
if [[ $xray_service == "running" ]]; then 
   status_xray="${YELL}ON✓${NC}"
else
   status_xray="${RED}🔴${NC} "
fi

# // STATUS SERVICE NGINX
if [[ $nginx_service == "running" ]]; then 
   status_nginx="${YELL}ON✓${NC}"
else
   status_nginx="${RED}🔴${NC} "
fi

# // STATUS SERVICE Dropbear
if [[ $dropbear_service == "running" ]]; then 
   status_dropbear="${YELL}ON✓${NC}"
else
   status_dropbear="${RED}🔴${NC} "
fi

# // INFOAKUN
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let vla=$vlx/2
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let vma=$vmc/2
ssh1="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let trb=$trx/2
ssx=$(grep -c -E "^#ss# " "/etc/xray/config.json")
let ssa=$ssx/2
########

KANAN="\033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC"
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m$NC"

########
r="\033[1;31m"  #REDTERANG
a=" ${CYAN}ACCOUNT PREMIUM" 
echo -e " "
echo -e " ${NC} ╭══════════════════════════════════════════════════════════╮"
echo -e " ${NC} │${bwhite}\033[41m        Welcome To Script Premium Gemilang Kinasih        ${NC}│"
echo -e " ${NC} ╰══════════════════════════════════════════════════════════╯"
echo -e " ${NC} ╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${NC} │$breed ⇲$bblue System OS     $YELL=$NC $MODEL"
echo -e " ${NC} │$breed ⇲$bblue Server RAM    $YELL=$NC $tram / $uram MB"
echo -e " ${NC} │$breed ⇲$bblue Uptime Server $YELL=$NC $SERONLINE"
echo -e " ${NC} │$breed ⇲$bblue Date          $YELL=$NC $DATEVPS"
echo -e " ${NC} │$breed ⇲$bblue Time          $YELL=$NC $TIMEZONE"
echo -e " ${NC} │$breed ⇲$bblue Domain        $YELL=$breed $domain"
echo -e " ${NC} │$breed ⇲$bblue IP VPS        $YELL=$bgreen $IPVPS"
echo -e " ${NC} ╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${NC}          ${KIRI} INFORMATION ACCOUNT ${KANAN}"
echo -e "           ════════════════════════════════════════════════${NC}" | lolcat 
echo -e " ${breed}          SSH/OPENVPN/UDP $YELL=$NC $ssh1${YELL}" "$a"
echo -e " ${breed}          VMESS/WS/GRPC   $YELL=$NC $vma${YELL}" "$a"
echo -e " ${breed}          VLESS/WS/GRPC   $YELL=$NC $vla${YELL}" "$a"
echo -e " ${breed}          TROJAN/WS/GRPC  $YELL=$NC $trb${YELL}" "$a"
echo -e " ${breed}          SHADOW/WS/GRP   $YELL=$NC $ssa${YELL}" "$a"
echo -e "           ════════════════════════════════════════════════${NC}" | lolcat 
echo -e " ${NC}      ${KIRI} WHATSAPP ADMIN 087786741106 ${KANAN}"
echo -e " ${NC} ╭════════════════╮╭══════════════════╮╭════════════════════╮${NC}"
echo -e " ${NC} │${bblue}  WS-ePRO$NC : $status_ws_epro   $bblue DROPBEAR${NC} : ON✓     $bblue HAPROXY${NC} : $status_dropbear      $NC│" 
echo -e " ${NC} │${bblue}  SSH$NC : $status_ssh   $bblue NGINX$NC : $status_nginx     $bblue XRAY$NC : $status_xray      $NC│" 
echo -e " ${NC} ╰════════════════╯╰══════════════════╯╰════════════════════╯${NC}"
echo -e " ${NC} ╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${NC} │$NC [${breed}01${NC}]$YELL MENU SSH     ${NC}│ [${breed}08${NC}]$YELL DELL ALL EXP  ${NC}│ [${breed}15${NC}]$YELL BCKP/RSTR   $NC}│$NC"
echo -e " ${NC} │$NC [${breed}02${NC}]$YELL MENU VMESS   ${NC}│ [${breed}09${NC}]$YELL AUTOREBOOT    ${NC}│ [${breed}16${NC}]$YELL REBOOT      $NC}│$NC"    
echo -e " ${NC} │$NC [${breed}03${NC}]$YELL MENU VLESS   ${NC}│ [${breed}10${NC}]$YELL INFO PORT     ${NC}│ [${breed}17${NC}]$YELL RESTART     $NC}│$NC"   
echo -e " ${NC} │$NC [${breed}04${NC}]$YELL MENU TROJAN  ${NC}│ [${breed}11${NC}]$YELL SPEEDTEST     ${NC}│ [${breed}18${NC}]$YELL DOMAIN      $NC}│$NC" 
echo -e " ${NC} │$NC [${breed}05${NC}]$YELL MENU SHADOW  ${NC}│ [${breed}12${NC}]$YELL RUNNING       ${NC}│ [${breed}19${NC}]$YELL CERT SSL    $NC}│$NC"
echo -e " ${NC} │$NC [${breed}06${NC}]$YELL MENU TRIAL   ${NC}│ [${breed}13${NC}]$YELL CLEAR LOG     ${NC}│ [${breed}20${NC}]$YELL INS. UDP    $NC}│$NC"
echo -e " ${NC} │$NC [${breed}07${NC}]$YELL CEK RAM/CPU  ${NC}│ [${breed}14${NC}]$YELL CREATE SLOW   ${NC}│ [${breed}21${NC}]$YELL CLEAR CACHE $NC}│$NC"
echo -e " ${NC} │$NC [${breed}22${NC}]$YELL CEK BANDWITH ${NC}| [${breed}23${NC}]$YELL UPDATE SCRIPT ${NC}| [${breed}24${NC}]$YELL MENU BOT    $NC}│$NC"
echo -e " ${NC} │                                                          $NC${z}│$NC"
echo -e " ${NC} │$NC [${breed}25${NC}]$bblue CHANGE BANNER SSH$NC ${KANAN} \E[0m\033[0;34m                              $NC${z}│$NC"
echo -e " ${NC} │$NC [${breed}26${NC}]$bblue LOG CREATE USER ACCOUNT ${KANAN} \E[0m\033[0;34m                        $NC${z}│$NC"
echo -e " ${NC} ╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " ${NC} ╭══════════════════════════════════════════════════════════╮${NC}"
echo -e " ${NC} │$NC$bblue Version       ${YELL}=$NC V4.1"
echo -e " ${NC} │$NC$bblue Client Name   ${YELL}=$bgreen $username"
echo -e " ${NC} │$NC$bblue Script Status ${YELL}=$NC $sts "
echo -e " ${NC} │$NC$bblue Expiry script ${YELL}=$green $exp ($r $certifacate ${NC}Days )"
echo -e " ${NC} ╰══════════════════════════════════════════════════════════╯${NC}"
echo -e " "
read -p " Select menu : " opt
echo -e ""

case $opt in
1 | 01)
clear
m-sshws
;;
2 | 02)
clear
m-vmess
;;
3 | 03)
clear
m-vless
;;
4 | 04)
clear
m-trojan
;;
5 | 05)
clear
m-ssws
;;
6 | 06)
clear
m-trial
;;
7 | 07)
clear
gotop
echo ""
echo -e " ${green} Back to menu in 1 sec ${NC}"
sleep 1
menu
;;
8 | 08)
clear
xp
echo ""
echo -e " ${green} Back to menu in 1 sec ${NC}"
sleep 1
menu
;;
9 | 09)
clear
autoreboot
;;
10)
clear
prot
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
11)
clear
speedtest
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
;;
12)
clear
run
;;
13)
clear
clearlog
;;
14)
clear
sd
;;
15)
clear
menu-backup
;;
16)
clear
reboot
;;
17)
clear
restart
;;
18)
clear
addhost
;;
19)
clear
fixcert
;;
20)
clear
echo -e "${green} ANDA YAKIN UNTUK MEMASANG SCRIPT INI ? $NC"
echo -e "${green} MINIMAL RAM 2 GB BIAR DISK TIDAK FULL $NC"
echo -e "${green} OS SUPPORT UBUNTU 20.04 ONLY $NC"
echo -e ""
read -p "SUDAH LAPOR KE ADMIN ? [Y/N]:" arg
if [[ $arg == 'Y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  echo -e "${green}START. . . $NC"
elif [[ $arg == 'y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  clear
  echo -e "${Blue}START . . .$NC"
elif [[ $arg == 'N' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  menu
  exit 0
elif [[ $arg == 'n' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  rm -f /root/update.sh
  exit 0
else
  echo -e "${RED}Argumen Tidak Diketahui! $NC"
  sleep 1
  clear
  rm -f /root/update.sh
  exit 0
fi

##########
clear
wget --load-cookies /tmp/cookies.txt ${UDPX} -O install-udp && rm -rf /tmp/cookies.txt && chmod +x install-udp && ./install-udp
;;
21)
clear
clearcache
;;
22)
clear
bw
;;
23)
clear
wget -q https://raw.githubusercontent.com/gemilangkinasih/Autoscript/GM/update.sh
chmod +x update.sh
./update.sh
;;
24)
clear
m-bot
;;
25)
clear
echo -e "Edit Banner SSH Message " | lolcat
sleep 2
echo -e "Loading......YELL" | lolcat
sleep 5
nano /etc/kyt.txt
clear
echo -e "${green}ANDA YAKIN UNTUK MEMASANG BANNER INI ? $NC"
echo -e ""
read -p "SILAHKAN PILIH OPSI BERIKUT [Y/N]:" arg
if [[ $arg == 'Y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  echo -e "${green}START. . . $NC"
elif [[ $arg == 'y' ]]; then
  echo -e "${Blue}Tindakan Diteruskan! $NC"
  clear
  echo -e "${Blue}START . . .$NC"
elif [[ $arg == 'N' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  menu
  exit 0
elif [[ $arg == 'n' ]]; then
  echo -e "${RED}Tindakan Dihentikan! $NC"
  sleep 1
  clear
  rm -f /root/update.sh
  exit 0
else
  echo -e "${RED}Argumen Tidak Diketahui! $NC"
  sleep 1
  clear
  rm -f /root/update.sh
  exit 0
fi
##########
clear
reboot
;;
26)
clear
cat /etc/user-create/user.log
echo ""
read -p "Press enter Back To menu"
menu
;;
0 | 00)
exit
;;
x)
menu
;;
*) clear ;
echo -e ""
menu
;;
esac
